-- Run in the Supabase SQL editor (Project > SQL Editor > New query) for the
-- "ware-assets" project. Safe to re-run: it only does anything the first
-- time.
--
-- Gives every chat visitor a number ("Visitor 12" in the Chats page instead
-- of "Anonymous visitor"), in the order they first chatted. A number never
-- changes, and deleting a chat doesn't renumber the others.

do $$
declare
  highest bigint;
begin
  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'chat_conversations'
      and column_name = 'visitor_number'
  ) then
    alter table public.chat_conversations
      add column visitor_number bigint generated by default as identity;

    -- Existing chats: oldest first.
    with ordered as (
      select id, row_number() over (order by started_at, id) as n
      from public.chat_conversations
    )
    update public.chat_conversations c
    set visitor_number = o.n
    from ordered o
    where c.id = o.id;

    -- New visitors carry on from there.
    select coalesce(max(visitor_number), 0) into highest
    from public.chat_conversations;
    if highest > 0 then
      perform setval(
        pg_get_serial_sequence('public.chat_conversations', 'visitor_number'),
        highest
      );
    end if;
  end if;
end $$;
